apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 18-ubi8
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: '{{ .Values.build.source.git.uri }}'
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  lookupPolicy:
    local: {{ .Values.imagestream.lookupPolicy.local }}
