apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: bagel-8b-v1.0
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: bagel-8b-v1.0
  namespace: fihr-rag-serving
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--dtype=float16'
        - '--tensor-parallel-size=2'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '10'
          memory: 20Gi
          nvidia.com/gpu: '2'
        requests:
          cpu: '6'
          memory: 16Gi
          nvidia.com/gpu: '2'
      runtime: bagel-8b-v1.0
      storage:
        key: aws-connection-aws-s3-models
        path: models/bagel-8b-v1.0
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
