{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: ai-hackathon-starter-backend
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: {{ .Values.route.host | default (printf "%s-%s.apps.%s.%s" .Release.Name .Release.Namespace .Values.cluster.name .Values.cluster.domain) }}
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  port:
    targetPort: "{{ .Values.containerPort }}-tcp"
  tls:
    termination: {{ .Values.route.tls.termination | quote }}
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
