kind: Secret
apiVersion: v1
metadata:
  name: credential-goalsetter-keycloak
  namespace: goalsetter
  labels:
    app: keycloak
    keycloak: goalsetter-keycloak
data:
  ADMIN_PASSWORD: xxxxxxx
  ADMIN_USERNAME: xxxxxxx
type: Opaque
