apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    template: postgresql-persistent-template
  annotations:
    template.openshift.io/expose-database_name: '{.data["database-name"]}'
    template.openshift.io/expose-password: '{.data["database-password"]}'
    template.openshift.io/expose-username: '{.data["database-user"]}'
type: Opaque
data:
  database-name: {{ .Values.database.name | b64enc }}
  database-password: {{ .Values.database.password | b64enc }}
  database-user: {{ .Values.database.user | b64enc }}