kind: ConfigMap
apiVersion: v1
metadata:
  name: quarkus-config
data:
  DB_PASSWORD:  {{ .Values.nl2sqldb.password }}
  DB_USERNAME: {{ .Values.nl2sqldb.username }}
  JDBC_URL: jdbc:postgresql://nl2sql-sample-postgresql-postgresql.{{.Release.Namespace}}.svc.cluster.local:5432/nl2sql-sample
  VLLM_API_URL: {{ .Values.vllmApiUrl }}
  
