kind: ConfigMap
apiVersion: v1
metadata:
  name: quarkus-config
data:
  DB_PASSWORD:  {{ .Values.nl2sqldb.password }}
  DB_USERNAME: {{ .Values.nl2sqldb.username }}
  JDBC_URL: {{ .Values.nl2sqldb.host }}
  VLLM_API_URL: {{ .Values.vllmApiUrl }}
  
