kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: goalora-landing-page-ssl
  labels:
    app: goalora-landing-page
    app.kubernetes.io/component: goalora-landing-page
    app.kubernetes.io/instance: goalora-landing-page
    app.kubernetes.io/name: goalora-landing-page
    app.kubernetes.io/part-of: goalora-landing-page
    app.openshift.io/runtime: httpd
    app.openshift.io/runtime-version: 2.4-el7
spec:
  host: goalora.com
  to:
    kind: Service
    name: goalora-landing-page
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIFHDCCBASgAwIBAgISA3skiiy8Hic1b01BAXudzuf5MA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMzA1MDMwNjI5MjBaFw0yMzA4MDEwNjI5MTlaMBYxFDASBgNVBAMT
      C2dvYWxvcmEuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArV8Q
      DiKnmc450+KHMv4fs0T9Yp0h4F7/fkvypclvY5VD8VkeAL5UbnHlQ4+63UnZ1WXx
      +fL+nrAbutfMMDMxlRTCIMBAqxPQy46V/1EUqp2WMam5m77EsP3EGBc4t8tQvWbn
      J1a8Zr+31j7h2qFBMYGp9QKTZdtP8KmYQi3PrKNXfHj61hn2QF2+Yp1YAV+m07Zk
      PPm1alHIWAAASPAGT8O1TaVZIANvXX4KerSo+dsWoZQp1FEhe2a92EyjUklJB74u
      3LlR7G0yXiAhWP8n8aJRhojgs00eD9e3S51jHeUEYXe32CvhT4ADYWfC3BmrMvzk
      zPSuAVrDnsEAG1wnwwIDAQABo4ICRjCCAkIwDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
      JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
      BBRwWHo6QC0+zTfaVJQeIf9mWoiYIjAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDm
      H6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5v
      LmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzAW
      BgNVHREEDzANggtnb2Fsb3JhLmNvbTBMBgNVHSAERTBDMAgGBmeBDAECATA3Bgsr
      BgEEAYLfEwEBATAoMCYGCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0
      Lm9yZzCCAQQGCisGAQQB1nkCBAIEgfUEgfIA8AB1ALc++yTfnE26dfI5xbpY9Gxd
      /ELPep81xJ4dCYEl7bSZAAABh+CEAucAAAQDAEYwRAIgdgaQ78qpdDKGRGZhQTRT
      OgMMFi5ipG5JbGLJagmiE1ACIHlHvA3+evugT04ZQMqvdSC5ueavw4Jmjqcb0ZQY
      GfrWAHcArfe++nz/EMiLnT2cHj4YarRnKV3PsQwkyoWGNOvcgooAAAGH4IQDLAAA
      BAMASDBGAiEA4ED+FymdPwe2gDlBGy1u3AV3xbio+GInnpcT1BhqfmsCIQCXZcJe
      t59UW3kYl3Gy0pPaeTH5y588iRet0gvLbrvH1DANBgkqhkiG9w0BAQsFAAOCAQEA
      XSl+/SNYfnEmqNgwvlIf7RHkFOg79IhjvXq0Q36VU4tKRfTBXxIKOK5qsIMjz+Ic
      iiss7OUT6ooOgt1K8MdYACmpqhGI/pJ7aBKO4yDici2S6WM12Qfnnqnc1f9AFO7N
      sHWVfQgJ1OZMYKyluWvhqEGA8RJZLaW/ayIqz4CrazpzQ3dYu8yHf5dBBkKmSw+s
      hVJB4xg0kOf+sEd7XZ3kizTgndxjYf1B7SKzFljmVGjxcFnYyztAFBIVILxD+F4h
      RrgPS+c0s3k2ZAIqelmdI5CqdczM6V/gdhf+RKCYbKFljc8/8usg0iJfG/qf7i2m
      oKaDnqckDcyq/zQoLV0G0A==
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtXxAOIqeZzjnT
      4ocy/h+zRP1inSHgXv9+S/KlyW9jlUPxWR4AvlRuceVDj7rdSdnVZfH58v6esBu6
      18wwMzGVFMIgwECrE9DLjpX/URSqnZYxqbmbvsSw/cQYFzi3y1C9ZucnVrxmv7fW
      PuHaoUExgan1ApNl20/wqZhCLc+so1d8ePrWGfZAXb5inVgBX6bTtmQ8+bVqUchY
      AABI8AZPw7VNpVkgA29dfgp6tKj52xahlCnUUSF7Zr3YTKNSSUkHvi7cuVHsbTJe
      ICFY/yfxolGGiOCzTR4P17dLnWMd5QRhd7fYK+FPgANhZ8LcGasy/OTM9K4BWsOe
      wQAbXCfDAgMBAAECggEAMbP5sdu8iesmB/k/Al75bpceP3nF3wHNJIOYfnAH55hA
      4L3ITLVEFl+/twVLMKq98SBnZV2FIrBhWskIKF9c3R0U5HfJcmJdbyYjGY3Aq4M/
      LmC2rhBcalNuNuvdXk/DB3GrXktO+vQGu7zOWjP1sUA3nd7NrBtaSSgN1xc0HQ1E
      ONf0bQMuZF8lwAHUsuVvE8AA1PA2X+P421awbdOKguPdHvErJZKHUR2Relg2WzJc
      sqt9G+LKLwJ4kBA18bTqm1EFqPhpLmj5HtqfTywCicHorlGcDaaxocaQZEm1NB6H
      yO1IHZVy0xKlK/OpXc5kp8jI/fLWCLuwG7AJPGwEFQKBgQDRY6dZNTsHeiiXnI57
      Y4L0fK8Ml4UD5ngBEm11T5AtIdAPNKEBQqfwBCvKpy31mhfCoVTdDnAd2qoqI998
      Pi4oxz/ZryXBxJT9OK0f8GpH03Yg0haxjoy+R4u8ZhZJKfUWfNwimyWX/9RU5NjT
      +vs5DV0NEnQIqcfdl2uvVlryrQKBgQDT9uAt+FLfRlHKUROSxxqvgN0+50lAY519
      WZgh5ufYYiN5QmLsI6suF5ZauVJwGaFcjqgtYcEhQIvbyE8RWON/BtfFFwoDWMqi
      5qBQfG+nqhQYOwpHaCHd1LvseCfYvMrO7FNauCR0Q82o7tKllQuHEPgannh/hiKs
      627yIp1CLwKBgGF4HQ92quq5H6ork1u2n+AFJksbQSzmnJgLJu7DwZ5wrfRWEFiQ
      2bHtjyD/n3JDb6oHBYT9Uo1jG3EQT9j67OvIjF1dnZrMUnppZpWGiUK0Gbn/cdbn
      P3bXwSFK+DbIlDEKoEJvrBlMWl/GQ3Sx0T3mjZknLOJXfhUVhmgRL7blAoGBAKNA
      xbEiTVHCK0ST5WtrBlad/clxAa4iCy58TvvtiCvUilXel6ogXruFVzxQ9/l3BBzx
      kv5BCCrAN/fy81L9D1rKvm0CLagePxPwZREYhjawfAGdl3Ef9tWP/51FfgskfV+a
      DSkWIp2Zi1DNgFgfz10b6Ls3yr8NZK+iNTUxC8XpAoGBAL39PI8t8Fe9+j8xJQ3V
      MXCjFjkJGut/qbMWxX1S+X+YMUNkcr6Gb4ga1qTUOfyil8Ia7vRPrdsWe8Op1Ksl
      C14omHx6m4zQY09TYd+0FWSodex/kUj+NWns8FImjAVwJ642sCHulhmZnWyG3W1H
      fVPNCZcEC8ph0w9Jcv7/TvlZ
      -----END PRIVATE KEY-----
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIFHDCCBASgAwIBAgISA3skiiy8Hic1b01BAXudzuf5MA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMzA1MDMwNjI5MjBaFw0yMzA4MDEwNjI5MTlaMBYxFDASBgNVBAMT
      C2dvYWxvcmEuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArV8Q
      DiKnmc450+KHMv4fs0T9Yp0h4F7/fkvypclvY5VD8VkeAL5UbnHlQ4+63UnZ1WXx
      +fL+nrAbutfMMDMxlRTCIMBAqxPQy46V/1EUqp2WMam5m77EsP3EGBc4t8tQvWbn
      J1a8Zr+31j7h2qFBMYGp9QKTZdtP8KmYQi3PrKNXfHj61hn2QF2+Yp1YAV+m07Zk
      PPm1alHIWAAASPAGT8O1TaVZIANvXX4KerSo+dsWoZQp1FEhe2a92EyjUklJB74u
      3LlR7G0yXiAhWP8n8aJRhojgs00eD9e3S51jHeUEYXe32CvhT4ADYWfC3BmrMvzk
      zPSuAVrDnsEAG1wnwwIDAQABo4ICRjCCAkIwDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
      JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
      BBRwWHo6QC0+zTfaVJQeIf9mWoiYIjAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDm
      H6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5v
      LmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzAW
      BgNVHREEDzANggtnb2Fsb3JhLmNvbTBMBgNVHSAERTBDMAgGBmeBDAECATA3Bgsr
      BgEEAYLfEwEBATAoMCYGCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0
      Lm9yZzCCAQQGCisGAQQB1nkCBAIEgfUEgfIA8AB1ALc++yTfnE26dfI5xbpY9Gxd
      /ELPep81xJ4dCYEl7bSZAAABh+CEAucAAAQDAEYwRAIgdgaQ78qpdDKGRGZhQTRT
      OgMMFi5ipG5JbGLJagmiE1ACIHlHvA3+evugT04ZQMqvdSC5ueavw4Jmjqcb0ZQY
      GfrWAHcArfe++nz/EMiLnT2cHj4YarRnKV3PsQwkyoWGNOvcgooAAAGH4IQDLAAA
      BAMASDBGAiEA4ED+FymdPwe2gDlBGy1u3AV3xbio+GInnpcT1BhqfmsCIQCXZcJe
      t59UW3kYl3Gy0pPaeTH5y588iRet0gvLbrvH1DANBgkqhkiG9w0BAQsFAAOCAQEA
      XSl+/SNYfnEmqNgwvlIf7RHkFOg79IhjvXq0Q36VU4tKRfTBXxIKOK5qsIMjz+Ic
      iiss7OUT6ooOgt1K8MdYACmpqhGI/pJ7aBKO4yDici2S6WM12Qfnnqnc1f9AFO7N
      sHWVfQgJ1OZMYKyluWvhqEGA8RJZLaW/ayIqz4CrazpzQ3dYu8yHf5dBBkKmSw+s
      hVJB4xg0kOf+sEd7XZ3kizTgndxjYf1B7SKzFljmVGjxcFnYyztAFBIVILxD+F4h
      RrgPS+c0s3k2ZAIqelmdI5CqdczM6V/gdhf+RKCYbKFljc8/8usg0iJfG/qf7i2m
      oKaDnqckDcyq/zQoLV0G0A==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
      MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
      DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
      ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
      wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
      LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
      4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
      bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
      sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
      Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
      FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
      SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
      PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
      TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
      SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
      c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
      +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
      ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
      b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
      U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
      MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
      5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
      9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
      WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
      he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
      Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None