apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: {{ .Values.embeddingmodel.name }}
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: {{ .Values.embeddingmodel.name }}
  namespace:  {{ .Release.Namespace}}
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: {{ .Values.predictor.maxReplicas }}
    minReplicas: {{ .Values.predictor.minReplicas }}
    model:
      args:
{{ toYaml .Values.embeddingmodel.args | indent 8 }}
      modelFormat:
        name: {{ .Values.embeddingmodel.modelFormat.name }}
      name: ''
      resources:
{{ toYaml .Values.embeddingmodel.resources | indent 8 }}
      runtime: {{ .Values.embeddingmodel.runtime }}
      storage:
        key: {{ .Values.embeddingmodel.storage.key }}
        path: models/{{ .Values.embeddingmodel.name }}
    tolerations:
{{ toYaml .Values.predictor.tolerations | indent 6 }}
