apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: migrated-gpu
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM ServingRuntime for KServe
    opendatahub.io/template-name: vllm-runtime
    openshift.io/display-name: {{ .Values.model.name }}
  name: {{ .Values.model.name }}
  namespace:  {{ .Values.namespace}}
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '{{ .Values.prometheus.service.port }}'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{.Values.model.name}}'
      command:
{{ toYaml .Values.container.command | indent 8 }}
      env:
{{ toYaml .Values.container.env | indent 8 }}
      image: '{{ .Values.image.repository }}@{{ .Values.image.digest }}'
      name: {{ .Values.container.name }}
      ports:
        - containerPort: {{ .Values.prometheus.service.port }}
          protocol: TCP
      volumeMounts:
{{ toYaml .Values.container.volumeMounts | indent 8 }}
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: {{ .Values.model.modelFormat.name }}
  volumes:
{{ toYaml .Values.volumes | indent 4 }}
