apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: cert-manager
  name: keycloak-certs-letsencrypt
  namespace: raft-infra
spec:
  secretTemplate:
    labels:
      app: cert-manager
  renewBefore: 720h
  subject:
    organizations:
      - Org Name
  duration: 2160h
  commonName: keycloak-raft-infra.apps.salamander.aimlworkbench.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
  secretName: keycloak-certs-letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 2048
  dnsNames:
    - keycloak-raft-infra.apps.salamander.aimlworkbench.com