kind: Keycloak
apiVersion: k8s.keycloak.org/v2alpha1
metadata:
  name: raft-keycloak
  labels:
    app: sso
  namespace: raft-infra
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgresql-keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  hostname:
    hostname: strapi-raft-infra.apps.salamander.aimlworkbench.com
  http:
    tlsSecret: keycloak-certs-letsencrypt