apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: ai-hackathon-starter-kit-keycloak
spec:
  instances: 1
  selector: 'app=keycloak,app.kubernetes.io/managed-by=keycloak-operator,app.kubernetes.io/instance=ai-hackathon-starter-kit-keycloak'
