kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/purefield-demo-team/ai-hackathon-starter.git'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"strapi:latest","namespace":"ai-hackathon-starter-kit"},"fieldPath":"spec.template.spec.containers[?(@.name==\"strapi\")].image","paused":"false"}]'
    openshift.io/generated-by: OpenShiftWebConsole
  name: strapi
  labels:
    app: strapi
    app.kubernetes.io/component: strapi
    app.kubernetes.io/instance: strapi
    app.kubernetes.io/name: strapi
    app.kubernetes.io/part-of: ai-hackathon-starter-backend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 18-ubi8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strapi
        deployment: strapi
    spec:
      containers:
        - name: strapi
          image: 'image-registry.openshift-image-registry.svc:5000/{{namespace}}/strapi:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600