kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/purefield-demo-team/ai-hackathon-starter.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: strapi
  labels:
    app: strapi
    app.kubernetes.io/component: strapi
    app.kubernetes.io/instance: strapi
    app.kubernetes.io/name: strapi
    app.kubernetes.io/part-of: ai-hackathon-starter-backend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 18-ubi8
spec:
  lookupPolicy:
    local: false