kind: Service
apiVersion: v1
metadata:
  name: strapi
  labels:
    app: strapi
    app.kubernetes.io/component: strapi
    app.kubernetes.io/instance: strapi
    app.kubernetes.io/name: strapi
    app.kubernetes.io/part-of: strapi
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  ports:
    - name: 1337-tcp
      protocol: TCP
      port: 1337
      targetPort: 1337
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: strapi
    deployment: strapi
