kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: strapi
  namespace: goalsetter
  labels:
    app: strapi
    app.kubernetes.io/component: strapi
    app.kubernetes.io/instance: strapi
    app.kubernetes.io/name: strapi
    app.kubernetes.io/part-of: strapi
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  lookupPolicy:
    local: false
