kind: Deployment
apiVersion: apps/v1
metadata:
  name: strapi
  namespace: goalsetter
  labels:
    app: strapi
    app.kubernetes.io/component: strapi
    app.kubernetes.io/instance: strapi
    app.kubernetes.io/name: strapi
    app.kubernetes.io/part-of: strapi
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strapi
        deployment: strapi
    spec:
      containers:
        - name: strapi
          image: >-
            image-registry.openshift-image-registry.svc:5000/goalsetter/strapi
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
