kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: goalora-app-ssl
  namespace: goalsetter
  labels:
    app: goal-setter-react
    app.kubernetes.io/component: goal-setter-react
    app.kubernetes.io/instance: goal-setter-react
    app.kubernetes.io/name: goal-setter-react
    app.kubernetes.io/part-of: goal-setter-react
    app.openshift.io/runtime: httpd
    app.openshift.io/runtime-version: 2.4-el7
spec:
  host: app.goalora.com
  to:
    kind: Service
    name: goal-setter-react
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIFHzCCBAegAwIBAgISAwwND2ZYwSwIoB6cfvkGTXA8MA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMzA1MDMwNjU4MzlaFw0yMzA4MDEwNjU4MzhaMBgxFjAUBgNVBAMM
      DSouZ29hbG9yYS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCo
      E0wKq2nGKVt0DXGjabVVISVnKa9iE9MC7jiahq33zPVfqILrdaIDNnBInSDkiP6k
      kM2n48ML+TO/4cwXDiXYMkVpwMN2GOKuL1hBwm6UPU6IwzbVmyLpy0CnsAPMIoDp
      rVEzfiMxyY732ebCwfP+5Mq10hFQWg+POkGCjUgZvQDCJherVuCvI8++DrlER0t2
      bDA/U1V6z0hX4ryojWznvPz2DQODoHSGYGYpMJC6F12wSwy5sYKdjDtxWTmNdr+3
      GyN8zuS+N0/GKQlBPs9eHseehq1NM1MrgyA7rxfxXYRgCDP2YKDIB3WQ0Ecdi5cm
      xXN8KjqouNhe83OIXQa9AgMBAAGjggJHMIICQzAOBgNVHQ8BAf8EBAMCBaAwHQYD
      VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
      BBYEFOS9lj8C9UgLriokjmqZstXnSmFIMB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJ
      QOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3Iz
      Lm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcv
      MBgGA1UdEQQRMA+CDSouZ29hbG9yYS5jb20wTAYDVR0gBEUwQzAIBgZngQwBAgEw
      NwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5j
      cnlwdC5vcmcwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdQC3Pvsk35xNunXyOcW6
      WPRsXfxCz3qfNcSeHQmBJe20mQAAAYfgntnaAAAEAwBGMEQCICIsCz02CHHy4aRZ
      7xGVCAebodfNx0MFPHQG2r6HkyfXAiAqHnvN+flSMocVk+hxIRoSuEcyxJo/2ZBB
      R6PxAUgWuQB2AK33vvp8/xDIi509nB4+GGq0Zyldz7EMJMqFhjTr3IKKAAABh+Ce
      2f8AAAQDAEcwRQIgEf/Nk4ouGhzV4aKVomHz++5eC1AwAAJDauwjx0c4WPgCIQC2
      NNMsiT75A1BJzLCP+NZIfU3+IRhtMewHuJ/qW1eCoTANBgkqhkiG9w0BAQsFAAOC
      AQEARpta6p+erUXASWGgU6qQu9NwsF4TNPh8MMv7V7osrsI/8Yrh4d2APcy3urp9
      1NfWA6ZP91B+iJMENFSJ6CLU9ed//+6LPHKmqmgzJXuYOSIrtjGxNpGzKn0hSkbX
      9bxk8lIVx9k2kXjF6pJlwpXQzsaznf3PHpobLjdBPq+BxM7h1g6z4YHkV3+880r1
      hHonrRAalrlgJ6P1FSoo+N8py6mpL8pErgZzhyfJmNqvyV2DikB9UcAOANTASJye
      pQIWtjYbwfCwkDPfpyc9v3JcEfF614n1Babtbo29Uxa/xdvbZZb60mSGSYh2mLvz
      ZBQRb3T2i6eQD/xaHR45HeFISg==
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCoE0wKq2nGKVt0
      DXGjabVVISVnKa9iE9MC7jiahq33zPVfqILrdaIDNnBInSDkiP6kkM2n48ML+TO/
      4cwXDiXYMkVpwMN2GOKuL1hBwm6UPU6IwzbVmyLpy0CnsAPMIoDprVEzfiMxyY73
      2ebCwfP+5Mq10hFQWg+POkGCjUgZvQDCJherVuCvI8++DrlER0t2bDA/U1V6z0hX
      4ryojWznvPz2DQODoHSGYGYpMJC6F12wSwy5sYKdjDtxWTmNdr+3GyN8zuS+N0/G
      KQlBPs9eHseehq1NM1MrgyA7rxfxXYRgCDP2YKDIB3WQ0Ecdi5cmxXN8KjqouNhe
      83OIXQa9AgMBAAECggEACBOoHkTwx/UuhnDR8rm7XTKpUgaN1y9fZV8bKPCkm6MF
      pJnos3xBs5iFXbWKG9yQd7CLGkPZ8hfNrcbuqfbD702x8Ij/0f6t2ZOy9xmeLj37
      w05pDDh3CksHGZ43l7L0K0ApErzyrIURO3+RzqI65/2vI+MkvvRNyWlFHIsbbKJV
      XXudiID6MoXjG1/zAci+AsEVI4EWXocthz9NLQj3oW93s/xQ1yQfWAz40snMlKUo
      p78u/fGsfM4BBDHUEUeZ94va04UIQMlr7HGCyxw3BnQ2+vkQjgCRwzssMlKdomrP
      M56/yJZIdlFWPvseyhRPei9n4QbsSDchGk7cYiNGuQKBgQC2+yNHSgFbTPPS8pKI
      yh20fSfvi9utbabrWYng+reFrOo0hYCZB2AJUIecUVmr1I2RvmTwyDQqR3i1RYLk
      hvU2kBSorzoA4SZNXLnK1l8Mw5YjDc9L5oavrAUVb8S2kM3GQ3WdwEWQFFYIJtaU
      GFYHwkwVdHhkWhWYXoWZCbFptQKBgQDrJXBtfEBTUKWlvXAzeVVZzklvciv8HeQI
      gI/Qae/5gstwjWMweHVk/XLp/sYdcrzwJ1E4sCZxa0GVXSNTaUWSJaElXmvlOTop
      +yA0sqyBjnrSQevq9xDeL9lTJWUU+i+BgH1zsrumrPiC7M4L9tVtDJrJgjSkj4tM
      JJJ1InMt6QKBgQCJrXbC6gURTFpdS5VEBUfKiS0mSYZV/J5OkQV0WVEC7LMgJ582
      BV2WRJh03qTo7DpFAgvzO8A8W6CQTCgLiRwyHMDel1G+XaozJWTKIPhNo1BxOa/S
      /TY0Met1UK6ja1rZJeL2ejgdC6Ab7BUiQxlgJyqWLhdz8nAzQFOnbaqmzQKBgQDn
      zkqcw+Ytu8zwLGXVeIEZPPDLuoN90IGhmAst66E0GSowVFE50SX5XpjP7+ah1SBI
      ppm9Bnl/SbqnYd+XNKnuvsWzLveySs354KQJDzJbrXeKmo3VXaX1Qro86xpQqan3
      QhFp4wJ19wItHwCobrZLACf/CiqXJyKs90ihzEo7MQKBgHAxXO6sZBdXXHXth5JT
      U1ShujC1fvc8UecVgm0+mHBxfQ3oqaU/7UO8Jb6qhMqJ0aV9GE6DyKWIgBEGe3tM
      +XLlWQSvpIga1L3lef007RbwBbu5o1inQPl4sOhhku4uv7UH4l6NvXNHfuPX00nq
      nagdELae5eNbwvo8Ic1IwpgM
      -----END PRIVATE KEY-----
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIFHzCCBAegAwIBAgISAwwND2ZYwSwIoB6cfvkGTXA8MA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMzA1MDMwNjU4MzlaFw0yMzA4MDEwNjU4MzhaMBgxFjAUBgNVBAMM
      DSouZ29hbG9yYS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCo
      E0wKq2nGKVt0DXGjabVVISVnKa9iE9MC7jiahq33zPVfqILrdaIDNnBInSDkiP6k
      kM2n48ML+TO/4cwXDiXYMkVpwMN2GOKuL1hBwm6UPU6IwzbVmyLpy0CnsAPMIoDp
      rVEzfiMxyY732ebCwfP+5Mq10hFQWg+POkGCjUgZvQDCJherVuCvI8++DrlER0t2
      bDA/U1V6z0hX4ryojWznvPz2DQODoHSGYGYpMJC6F12wSwy5sYKdjDtxWTmNdr+3
      GyN8zuS+N0/GKQlBPs9eHseehq1NM1MrgyA7rxfxXYRgCDP2YKDIB3WQ0Ecdi5cm
      xXN8KjqouNhe83OIXQa9AgMBAAGjggJHMIICQzAOBgNVHQ8BAf8EBAMCBaAwHQYD
      VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
      BBYEFOS9lj8C9UgLriokjmqZstXnSmFIMB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJ
      QOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3Iz
      Lm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcv
      MBgGA1UdEQQRMA+CDSouZ29hbG9yYS5jb20wTAYDVR0gBEUwQzAIBgZngQwBAgEw
      NwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5j
      cnlwdC5vcmcwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdQC3Pvsk35xNunXyOcW6
      WPRsXfxCz3qfNcSeHQmBJe20mQAAAYfgntnaAAAEAwBGMEQCICIsCz02CHHy4aRZ
      7xGVCAebodfNx0MFPHQG2r6HkyfXAiAqHnvN+flSMocVk+hxIRoSuEcyxJo/2ZBB
      R6PxAUgWuQB2AK33vvp8/xDIi509nB4+GGq0Zyldz7EMJMqFhjTr3IKKAAABh+Ce
      2f8AAAQDAEcwRQIgEf/Nk4ouGhzV4aKVomHz++5eC1AwAAJDauwjx0c4WPgCIQC2
      NNMsiT75A1BJzLCP+NZIfU3+IRhtMewHuJ/qW1eCoTANBgkqhkiG9w0BAQsFAAOC
      AQEARpta6p+erUXASWGgU6qQu9NwsF4TNPh8MMv7V7osrsI/8Yrh4d2APcy3urp9
      1NfWA6ZP91B+iJMENFSJ6CLU9ed//+6LPHKmqmgzJXuYOSIrtjGxNpGzKn0hSkbX
      9bxk8lIVx9k2kXjF6pJlwpXQzsaznf3PHpobLjdBPq+BxM7h1g6z4YHkV3+880r1
      hHonrRAalrlgJ6P1FSoo+N8py6mpL8pErgZzhyfJmNqvyV2DikB9UcAOANTASJye
      pQIWtjYbwfCwkDPfpyc9v3JcEfF614n1Babtbo29Uxa/xdvbZZb60mSGSYh2mLvz
      ZBQRb3T2i6eQD/xaHR45HeFISg==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
      MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
      DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
      ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
      wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
      LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
      4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
      bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
      sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
      Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
      FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
      SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
      PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
      TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
      SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
      c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
      +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
      ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
      b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
      U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
      MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
      5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
      9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
      WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
      he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
      Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
