kind: Service
apiVersion: v1
metadata:
  name: stripe-backend
  labels:
    app: stripe-backend
    app.kubernetes.io/component: stripe-backend
    app.kubernetes.io/instance: stripe-backend
    app.kubernetes.io/name: stripe-backend
    app.kubernetes.io/part-of: stripe-backend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  ports:
    - name: 3001-tcp
      protocol: TCP
      port: 3001
      targetPort: 3001
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: stripe-backend
    deployment: stripe-backend