kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: stripe-backend
  labels:
    app: stripe-backend
    app.kubernetes.io/component: stripe-backend
    app.kubernetes.io/instance: stripe-backend
    app.kubernetes.io/name: stripe-backend
    app.kubernetes.io/part-of: stripe-backend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  lookupPolicy:
    local: false