apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: redis-stack-app
spec:
  lookupPolicy:
    local: {{ .Values.imageStream.lookupPolicy.local }}
  tags:
    {{- range .Values.imageStream.tags }}
    - name: {{ .name }}
      annotations:
        {{- range $key, $value := .annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      from:
        kind: {{ .from.kind }}
        name: {{ .from.name | quote }}
      generation: {{ .generation }}
      importPolicy:
        importMode: {{ .importPolicy.importMode }}
      referencePolicy:
        type: {{ .referencePolicy.type }}
    {{- end }}
