{{- if .Values.routes.redisinsight.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.routes.redisinsight.name }}
  labels:
    app: redis-stack
    app.kubernetes.io/component: redis-stack
    app.kubernetes.io/instance: redis-stack
    app.kubernetes.io/name: redis-stack
    app.kubernetes.io/part-of: redis-stack-app
    app.openshift.io/runtime-version: latest
  {{- if not .Values.routes.redisinsight.host }}
  annotations:
    openshift.io/host.generated: 'true'
  {{- end }}
spec:
  host: {{ .Values.routes.host | default (printf "%s-%s-%s.apps.%s.%s" .Release.Name .Values.routes.redisinsight.name .Release.Namespace .Values.cluster.name .Values.cluster.domain) }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: 100
  port:
    targetPort: {{ (index .Values.service.ports 1).name }}
  tls:
    termination: {{ .Values.routes.redisinsight.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.routes.redisinsight.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None
{{- end }}
