kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/purefield-demo-team/ai-hackathon-starter.git'
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '636812757'
  name: react-frontend
  labels:
    app: react-frontend
    app.kubernetes.io/component: react-frontend
    app.kubernetes.io/instance: react-frontend
    app.kubernetes.io/name: react-frontend
    app.kubernetes.io/part-of: ai-hackathon-starter-frontend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 18-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'react-frontend:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:18-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/purefield-demo-team/ai-hackathon-starter.git'
    contextDir: /react-frontend
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
