kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: redisinsight
  labels:
    app: redis-stack
    app.kubernetes.io/component: redis-stack
    app.kubernetes.io/instance: redis-stack
    app.kubernetes.io/name: redis-stack
    app.kubernetes.io/part-of: redis-stack-app
    app.openshift.io/runtime-version: latest
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: redis-insight-redis-search.apps.ocpai.enterprisewebservice.com
  to:
    kind: Service
    name: redis-stack
    weight: 100
  port:
    targetPort: 8001-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None