---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
  namespace: ai-hackathon-starter-kit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-db
  namespace: ai-hackathon-starter-kit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem


